### ISSUE TITLE
请问如何运行？

### ISSUE THREAD

**Issue by UJohn** [L8426936/auto.js-script#1]
Mac系统，解压后不知道怎么运行main.js

**Comment by L8426936** [comment]
运行方式1：手机安装[Auto.js](https://github.com/SuperMonster002/Hello_Sockpuppet/raw/master/%5Bauto.js%5D%5B4.1.1_alpha2%5D%5Barm-v7%5D(b69a4e23).apk?raw=true)，解压到auto.js脚本文件路径，运行main.js
运行方式2：安装“clear_friends/build/微信好友清理.apk”
