### ISSUE TITLE
如果上次聊天发的语音没有切换回来，会导致程序卡住

### ISSUE THREAD

**Issue by shy0511** [L8426936/auto.js-script#10]
如果上次聊天发的语音没有切换回来，更多功能的按钮的位置会不一样，没法打开转账按钮，程序卡住没法运行

**Comment by L8426936** [comment]
> 如果上次聊天发的语音没有切换回来，更多功能的按钮的位置会不一样，没法打开转账按钮，程序卡住没法运行

可以的话请加QQ：3339372910 详细交流
