### ISSUE TITLE
对方身份有异常时，程序无法进行判断

### ISSUE THREAD

**Issue by beijifengren** [L8426936/auto.js-script#12]
有的好友在转账的时候会出现交易提醒，请先完善交易信息，核实对方身份后，谨慎判断是否继续支付。当出现这个提醒的时候，无法进行判断，可否进行完善一下，非常感谢。

**Comment by L8426936** [comment]
> 有的好友在转账的时候会出现交易提醒，请先完善交易信息，核实对方身份后，谨慎判断是否继续支付。当出现这个提醒的时候，无法进行判断，可否进行完善一下，非常感谢。

这种情况我没法主动创造，如果你乐意帮忙的话，请加QQ：3339372910详聊

**Comment by beijifengren** [comment]
大佬效率真高，一会就完善了。非常感谢。
