### ISSUE TITLE
我3000多个好友，要等很久，可以做一个桌面版的后台工具吗，谢谢

### ISSUE THREAD

**Issue by GalaxySciTech** [L8426936/auto.js-script#14]
我3000多个好友，要等很久，可以做一个桌面版的后台工具吗，谢谢

**Comment by GalaxySciTech** [comment]
像wetool那样后台跑清理好友

**Comment by L8426936** [comment]
> 像wetool那样后台跑清理好友

这个项目是面向有手机，没电脑，对隐私比较注重的人
你的要求没法满足，你可以找找网上其它工具
速度一直致命问题，3000确实挺多的，你可以尝试分组好友，以黑或是白名单方式测试好友，以及睡觉前跑测试，一觉醒来基本就跑完了，没其它提高速度的方式了
