### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by MaximilianYeung** [L8426936/auto.js-script#15]
点击测试好友后崩溃

**Comment by L8426936** [comment]
> 点击测试好友后崩溃

请你把Auto.js的报错日志发上来，或者加QQ：3339372910详聊

**Comment by MaximilianYeung** [comment]
点击提交报错信息到github提示配置错误 使用运行方式二下载apk是没问题的

**Comment by L8426936** [comment]
> 点击提交报错信息到github提示配置错误

我写的脚本并没有"点击提交报错信息到github提示配置错误"这个提示，这个应该是Auto.js的问题；可能是Auto.js没有悬浮窗权限，因为我写的脚本要悬浮窗权限，但是我没做检查

**Comment by sstutu** [comment]
运行过程中卡死。重复提示更新，

**Comment by L8426936** [comment]
> 运行过程中卡死。重复提示更新，

尝试删除config/files_md5.json后，再次更新，你现在用的是哪个版本？
