### ISSUE TITLE
大部分实名微信用户都可以通过转账功能确认

### ISSUE THREAD

**Issue by young66** [L8426936/auto.js-script#16]
碰到有一个用户转账没有名字，但是可以正常发送消息。这种用户可能是未实名或者未绑定钱包银行卡用户。

**Comment by L8426936** [comment]
> 碰到有一个用户转账没有名字，但是可以正常发送消息。这种用户可能是未实名或者未绑定钱包银行卡用户。

这种好友可以转账吗？可以的转账的话，和已实名好友转账有不一样的地方吗？

**Comment by L8426936** [comment]
> 碰到有一个用户转账没有名字，但是可以正常发送消息。这种用户可能是未实名或者未绑定钱包银行卡用户。

我的好友列表也找到一个这种情况的，不影响脚本运行
