### ISSUE TITLE
看日志文件，程序 3 秒就结束运行了

### ISSUE THREAD

**Issue by heshangcode** [L8426936/auto.js-script#17]
手机：Redmi k40
微信：国内版：8.0.7

第一次使用，在通讯录页面只会检测前面的几个好友，然后就停止了，后面的好友不能检测，程序在页面上不会自动向下拉动。

第二次打开软件使用，日志里直接 3 秒结束。前几个好友也不检测了，后面的也不会检测，自动结束了
![image](https://user-images.githubusercontent.com/39662806/127122946-5ac6dfc4-380f-44ed-8310-dbb2d3cbe101.png)

**Comment by L8426936** [comment]
> 手机：Redmi k40
> 微信：国内版：8.0.7
> 
> 第一次使用，在通讯录页面只会检测前面的几个好友，然后就停止了，后面的好友不能检测，程序在页面上不会自动向下拉动。
> 
> 第二次打开软件使用，日志里直接 3 秒结束。前几个好友也不检测了，后面的也不会检测，自动结束了
> ![image](https://user-images.githubusercontent.com/39662806/127122946-5ac6dfc4-380f-44ed-8310-dbb2d3cbe101.png)

看这个日志我也不清楚什么情况，多尝试几次也会这样吗？不介意的话，加QQ：3339372910 详聊

**Comment by heshangcode** [comment]
> > 手机：Redmi k40
> > 微信：国内版：8.0.7
> > 第一次使用，在通讯录页面只会检测前面的几个好友，然后就停止了，后面的好友不能检测，程序在页面上不会自动向下拉动。
> > 第二次打开软件使用，日志里直接 3 秒结束。前几个好友也不检测了，后面的也不会检测，自动结束了
> > ![image](https://user-images.githubusercontent.com/39662806/127122946-5ac6dfc4-380f-44ed-8310-dbb2d3cbe101.png)
> 
> 看这个日志我也不清楚什么情况，多尝试几次也会这样吗？不介意的话，加QQ：3339372910 详聊

申请加 qq，不过一直没有被你同意，麻烦同意一下
