### ISSUE TITLE
微信已更新

### ISSUE THREAD

**Issue by duzhor** [L8426936/auto.js-script#18]
微信现已更新至8.0.15版本

**Comment by L8426936** [comment]
> 微信现已更新至8.0.15版本

微信8.0.14~8.0.15版本部分控件不能触发点击事件，要通过点击屏幕才可以触发，要较大改动代码才能保持原有功能，就没那么快更新了

**Comment by L8426936** [comment]
> 微信现已更新至8.0.15版本

更新啦
