### ISSUE TITLE
非常好用，已给star

### ISSUE THREAD

**Issue by syxvip** [L8426936/auto.js-script#2]
作者能否抽空加一个 ，（选中部分用户）批量发消息，以及自动改备注功能！我看源码里面有相应的函数

**Comment by syxvip** [comment]
发现一个小bug 检测僵尸粉，有的好友删除后，向他转账会提示检查好友关系，然后js会报错，停止运行！

**Comment by L8426936** [comment]
> 作者能否抽空加一个 ，（选中部分用户）批量发消息，以及自动改备注功能！我看源码里面有相应的函数

谢谢支持，我只专注检查、删除僵尸粉，不打算添加其它功能

**Comment by L8426936** [comment]
> 发现一个小bug 检测僵尸粉，有的好友删除后，向他转账会提示检查好友关系，然后js会报错，停止运行！

目前我只在honor6X测试过，如果你是使用Auto.js运行的，可以把log发上来，或者加我QQ（3339372910）交流一下

**Comment by syxvip** [comment]
已经发送好友请求
