### ISSUE TITLE
发消息卡住

### ISSUE THREAD

**Issue by EmDark** [L8426936/auto.js-script#21]
机型 华为Mate40p  在发消息窗口会卡住 , 有点击的痕迹, 但是打不开发消息窗口, 需手动点击 方可继续 ,

**Comment by L8426936** [comment]
> 机型 华为Mate40p 在发消息窗口会卡住 , 有点击的痕迹, 但是打不开发消息窗口, 需手动点击 方可继续 ,

把日志发上来，或者加我QQ、微信，后续我修改脚本还需要在你手机上验证

**Comment by L8426936** [comment]
> 机型 华为Mate40p 在发消息窗口会卡住 , 有点击的痕迹, 但是打不开发消息窗口, 需手动点击 方可继续 ,

应该是坐标操作方式点击发消息时，刚好朋友圈或者视频号出现略缩图影响到了。但是脚本有卡住重启功能，根据设置等待10~30秒即可
