### ISSUE TITLE
微信8.028无法使用

### ISSUE THREAD

**Issue by RQ-Y** [L8426936/auto.js-script#22]
微信8.028无法使用,可以更新一下吗

**Comment by L8426936** [comment]
> 微信8.028无法使用,可以更新一下吗

已经停更了，你可以看这个[同步微信版本教程](https://github.com/L8426936/CleanUpWeChatZombieFans/blob/master/Make.md)修改配置文件，可能还能用

**Comment by RQ-Y** [comment]
ok
