### ISSUE TITLE
能否请适配未实名的微信号

### ISSUE THREAD

**Issue by GitMrLiHub** [L8426936/auto.js-script#24]
支持一个！试用了一下非常棒，但在用未实名的微信号的时候会卡住，能否适配一下呢

**Comment by L8426936** [comment]
感谢支持，已经不维护了。未实名的微信号的时候会卡住的情况，如果是[运行方式一](https://github.com/L8426936/CleanUpWeChatZombieFans#%E8%BF%90%E8%A1%8C%E6%96%B9%E5%BC%8F%E4%B8%80%E6%93%8D%E4%BD%9C%E7%B9%81%E7%90%90)，数十秒内会自动重新运行
