### ISSUE TITLE
有种情况会导致程序卡住

### ISSUE THREAD

**Issue by haotian-code** [L8426936/auto.js-script#5]
有种情况就是对方虽然没删掉或者拉黑你，但是对方注销了账号，点进去以后会没有发送信息的按钮，就会卡在这了，脚本不知该干啥了

**Comment by L8426936** [comment]
> 有种情况就是对方虽然没删掉或者拉黑你，但是对方注销了账号，点进去以后会没有发送信息的按钮，就会卡在这了，脚本不知该干啥了

能不能加我QQ交流一下，因为我没有好友是注销的

**Comment by L8426936** [comment]
> 有种情况就是对方虽然没删掉或者拉黑你，但是对方注销了账号，点进去以后会没有发送信息的按钮，就会卡在这了，脚本不知该干啥了

QQ：3339372910

**Comment by jnsday** [comment]
相同的情况~~~
界面示例如下：
http://mogu.misstang.store:65425/TestFail.jpg

**Comment by L8426936** [comment]
有该问题的请加QQ：3339372910

**Comment by L8426936** [comment]
> 相同的情况~~~
> 界面示例如下：
> http://mogu.misstang.store:65425/TestFail.jpg

请加QQ：3339372910
