### ISSUE TITLE
如何使用pc开发脚本，除了使用vscode的插件

### ISSUE THREAD

**Issue by PetersonLian** [L8426936/auto.js-script#6]
如题。
我目前只会用手机编写

**Comment by L8426936** [comment]
vscode的插件只是调试方便了，不用插件也可以啊。纯js开发文本编辑器就够啦

**Comment by L8426936** [comment]
> 如题。
> 我目前只会用手机编写

vscode的插件只是调试方便了，不用插件也可以啊。纯js开发文本编辑器就够啦
