### ISSUE TITLE
在点击确认转账后网络延迟的情况下会卡住

### ISSUE THREAD

**Issue by wmajwt** [L8426936/auto.js-script#9]
因为有时候手机卡顿或网络延迟，在输入0.01点击确认转账后微信会延迟出现无法转账的通知或者输入支付密码的界面，造成无法后退，程序卡住无法进行。
我尝试了做去下修改：
`    /**
     * 点击确认转账
     */
    function clickConfirmTransfer() {
        if (node_util.backtrackClickNode(id(ids["confirm_transfer"]).enabled().findOne())) {
            step = 7;
            sleep(5000);
        }
    }`
之后就可以顺利进行了，本人不懂编程，所以这种方式太笨拙，请大神对这一块进行优化

**Comment by L8426936** [comment]
> 因为有时候手机卡顿或网络延迟，在输入0.01点击确认转账后微信会延迟出现无法转账的通知或者输入支付密码的界面，造成无法后退，程序卡住无法进行。
> 我尝试了做去下修改：
> ` /** * 点击确认转账 */ function clickConfirmTransfer() { if (node_util.backtrackClickNode(id(ids["confirm_transfer"]).enabled().findOne())) { step = 7; sleep(5000); } }`
> 之后就可以顺利进行了，本人不懂编程，所以这种方式太笨拙，请大神对这一块进行优化

可以的话请加QQ：3339372910详细交流，话说都5G了还能网络延迟😑

**Comment by syxvip** [comment]
确实存在，我这网络不太好，基本一分钟卡一次  太难了哈哈

**Comment by lewisun7** [comment]
同遇到这个问题，经常卡在确认转账输入密码界面
